documents:
- name: mkdocs
  sources:
  - site/**/*.html
  hunspell:
    d: docs/src/dictionary/hunspell/en_US
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic
  filters:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - a.magiclink-compare
      - a.magiclink-commit
      - span.keys
      - .MathJax_Preview
      - .md-nav__link
      - .md-footer-custom-text
      - .md-source__repository
      - .headerlink
      - .md-icon

- name: markdown
  sources:
  - README.md
  hunspell:
    d: docs/src/dictionary/hunspell/en_US
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic
  filters:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre

- name: python
  sources:
  - setup.py
  - "{wcmatch,tests}/**/*.py"
  hunspell:
    d: docs/src/dictionary/hunspell/en_US
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/python.dic
  filters:
  - pyspelling.filters.python:
      strings: false
      comments: false
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\`~]
      delimiters:
        - open: (?P<open>`+)
          content: .*?
          close: (?P=open)
        - open: (?s)^(?P<open>\s*~{3,})
          content: .*?
          close: ^(?P=open)$
