[build-system]
requires = [
    "hatchling>=0.21.1",
]
build-backend = "hatchling.build"

[project]
name = "wcmatch"
description = "Wildcard/glob file name matcher."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Isaac Muse", email = "Isaac.Muse@gmail.com" },
]
keywords = [
    "glob",
    "fnmatch",
    "search",
    "wildcard"
]
dynamic = [
    "classifiers",
    "version",
]

dependencies = [
    "bracex>=3.0"
]

[project.urls]
Homepage = "https://github.com/facelessuser/wcmatch"

[tool.hatch.version]
source = "code"
path = "wcmatch/__meta__.py"

[tool.hatch.build.targets.wheel]
include = [
    "/wcmatch",
]

[tool.hatch.build.targets.sdist]
include = [
    "/docs/src/markdown/**/*.md",
    "/docs/src/markdown/**/*.gif",
    "/docs/src/markdown/**/*.png",
    "/docs/src/markdown/dictionary/*.txt",
    "/docs/theme/**/*.css",
    "/docs/theme/**/*.js",
    "/docs/theme/**/*.html",
    "/requirements/*.txt",
    "/wcmatch/**/*.py",
    "/wcmatch/py.typed",
    "/tests/**/*.py",
    "/tools/**/*.py",
    "/.pyspelling.yml",
    "/.coveragerc",
    "/mkdocs.yml"
]

[tool.mypy]
files = [
    "wcmatch"
]
strict = true
show_error_codes = true

[tool.hatch.metadata.hooks.custom]

[tool.ruff]
line-length = 120

lint.select = [
    "A",    # flake8-builtins
    "B",    # flake8-bugbear
    "D",    # pydocstyle
    "C4",   # flake8-comprehensions
    "N",    # pep8-naming
    "E",    # pycodestyle
    "F",    # pyflakes
    "PGH",  # pygrep-hooks
    "RUF",  # ruff
    # "UP",   # pyupgrade
    "W",    # pycodestyle
    "YTT",  # flake8-2020,
    "PERF"  # Perflint
]

lint.ignore = [
    "E741",
    "C416",
    "D202",
    "D401",
    "D212",
    "D203",
    "D417",
    "N802",
    "N801",
    "N803",
    "N806",
    "N818",
    "RUF012",
    "RUF005",
    "PGH004",
    "RUF022",
    "RUF023",
    "RUF100"
]

[tool.hatch.envs.dev]
dependencies = [
    "pytest",
    "pytest-cov",
    "coverage",
    "mypy",
    "ruff",
    "build"
]

[tool.hatch.envs.docs]
dependencies = [
    "zensical",
    "markdown",
    "pymdown-extensions",
    "zensical-pymdownx @ git+https://github.com/facelessuser/pymdownx-zensical-theme.git",
    "pymdown_lexers @ git+https://github.com/facelessuser/pymdown-lexers.git",
    "pyspelling",
    "build",
    "python-minifier"
]

[[tool.hatch.envs.dev.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]

[[tool.hatch.envs.dev-stdlib.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]

[tool.hatch.envs.dev.scripts]
types = "mypy"
tests = "pytest --cov wcmatch --cov-append --cov-report term-missing --cov-report xml --cov-report html:.cov tests"
lint = 'ruff check .'

[tool.hatch.envs.docs.scripts]
spellcheck = [
    "python -m zensical.main build -f zensical.yml --clean --strict; pyspelling"
]
clean = [
    "python -m zensical.main build -f zensical.yml --clean"
]
serve = [
    "python -m zensical.main serve -f zensical.yml"
]
build = [
    "python -m zensical.main build -f zensical.yml --clean"
]
